services:
  orderservice-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: orderservice-api
    ports:
      - "8090:80"
      - "8091:443"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=orderservice-db;Database=OrderServiceDb;User Id=sa;Password=OrderService123!;TrustServerCertificate=True;
      - ASPNETCORE_URLS=http://+:80
    depends_on:
      - orderservice-db


  orderservice-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderservice-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=OrderService123!
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - orderservice-data:/var/opt/mssql


networks:
  default:
    name: bookwithext-network
    external: true

volumes:
  orderservice-data: