version: '3.8'

services:
  orderservice-db:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: orderservice-db
    environment:
      - ACCEPT_EULA=Y
      - SA_PASSWORD=OrderService123!
      - MSSQL_PID=Express
    ports:
      - "1434:1433"
    volumes:
      - orderservice-data:/var/opt/mssql
    networks:
      - orderservice-network

networks:
  orderservice-network:
    driver: bridge

volumes:
  orderservice-data: